# Generated by Django 6.0.5 on 2026-08-04 04:17

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('author', models.CharField(default='TechShe Can Africa', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Spark, Ignite or Send 1 Student', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='event_flyers/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('registration_open', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(help_text='Example: TSC26-REG-01', max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('group', models.CharField(choices=[('REGISTRATION', 'Registration Links'), ('EXHIBITION', 'Exhibition & Business'), ('CORPORATE', 'Corporate Packages'), ('ADVERTISING', 'Programme Advertising'), ('BRANDING', 'Branding Opportunities'), ('SPONSORSHIP', 'Sponsorship Packages'), ('DONATION', 'General Support & Donations')], max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set the fixed base price. Use 0 for custom-only contributions.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('KES', 'KSh'), ('USD', 'USD')], default='KES', max_length=3)),
                ('is_vip', models.BooleanField(default=False, help_text='Displays the VIP intake form.')),
                ('is_custom_amount', models.BooleanField(default=False, help_text='Allows the user to enter a custom contribution amount.')),
                ('requires_standard_registration_fields', models.BooleanField(default=True, help_text='Collect full name, organization/title, phone, email and category.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_categories', to='website.event')),
            ],
            options={
                'verbose_name': 'Registration Category',
                'verbose_name_plural': 'Registration Categories',
                'ordering': ['display_order', 'link_id'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('organization_or_title', models.CharField(blank=True, max_length=250, verbose_name='Organization / Title / CBO')),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('national_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(default='Homa Bay', max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('vip_addons_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('KES', 'KSh'), ('USD', 'USD')], default='KES', max_length=3)),
                ('payment_reference', models.CharField(blank=True, help_text='Latest gateway transaction reference.', max_length=150, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('referral_code', models.CharField(blank=True, max_length=100)),
                ('additional_information', models.TextField(blank=True)),
                ('consent_to_record_storage', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid / Confirmed'), ('attended', 'Attended'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='website.event')),
                ('selected_contribution_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='website.contributiontier')),
                ('category_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='website.registrationcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contributiontier',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_tiers', to='website.registrationcategory'),
        ),
        migrations.CreateModel(
            name='VIPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_address', models.CharField(help_text='Example: Hon., H.E., Ambassador or Dr.', max_length=100)),
                ('official_bio', models.TextField(blank=True)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='vip_headshots/')),
                ('passport_or_id', models.CharField(blank=True, help_text='Required for diplomats and international delegates. Optional for other VIP categories.', max_length=100)),
                ('security_detail_size', models.PositiveIntegerField(default=0)),
                ('vehicle_details', models.TextField(blank=True, help_text='Motorcade, vehicle type and registration details.')),
                ('parking_requirements', models.TextField(blank=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('transport_coordination_needed', models.BooleanField(default=False)),
                ('transport_coordination_details', models.TextField(blank=True)),
                ('security_notification_required', models.BooleanField(default=False)),
                ('security_notification_completed', models.BooleanField(default=False)),
                ('dietary_requirements', models.CharField(blank=True, max_length=255)),
                ('accommodation_needed', models.BooleanField(default=False)),
                ('accommodation_details', models.TextField(blank=True)),
                ('accompanying_aides_count', models.PositiveIntegerField(default=0)),
                ('aides_fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('add_on_meet_greet', models.BooleanField(default=False, help_text='Private meet-and-greet slot: KSh 15,000.')),
                ('add_on_stage_shoutout', models.BooleanField(default=False, help_text='On-stage recognition or shout-out: KSh 10,000.')),
                ('add_on_fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_speaking', models.BooleanField(default=False)),
                ('speaking_or_presentation_notes', models.TextField(blank=True)),
                ('specific_request', models.TextField(blank=True)),
                ('rsvp_deadline', models.DateField(blank=True, null=True)),
                ('assigned_liaison', models.CharField(blank=True, help_text='Example: Mike or David', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_profile', to='website.eventregistration')),
            ],
            options={
                'verbose_name': 'VIP Profile',
                'verbose_name_plural': 'VIP Profiles',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PESAPAL', 'Pesapal'), ('FLUTTERWAVE', 'Flutterwave'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('MANUAL', 'Manual Payment'), ('OTHER', 'Other')], max_length=30)),
                ('merchant_reference', models.CharField(max_length=150, unique=True)),
                ('gateway_reference', models.CharField(blank=True, max_length=150)),
                ('checkout_request_id', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('KES', 'KSh'), ('USD', 'USD')], max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='website.eventregistration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant_reference'], name='website_pay_merchan_6b0b06_idx'), models.Index(fields=['gateway_reference'], name='website_pay_gateway_ab71c2_idx'), models.Index(fields=['checkout_request_id'], name='website_pay_checkou_4a4493_idx'), models.Index(fields=['status'], name='website_pay_status_5422ff_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='registrationcategory',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_registration_category_slug_per_event'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='website_eve_event_i_630977_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['email'], name='website_eve_email_ae5ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['payment_reference'], name='website_eve_payment_a2e2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['utm_source'], name='website_eve_utm_sou_4f4c85_idx'),
        ),
        migrations.AddConstraint(
            model_name='contributiontier',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_contribution_tier_name_per_category'),
        ),
    ]
